// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: probe/v1/probe.proto

package probe_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_probe_v1_probe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_probe_v1_probe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_probe_v1_probe_proto_rawDescGZIP(), []int{0}
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_probe_v1_probe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_probe_v1_probe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_probe_v1_probe_proto_rawDescGZIP(), []int{1}
}

var File_probe_v1_probe_proto protoreflect.FileDescriptor

const file_probe_v1_probe_proto_rawDesc = "" +
	"\n" +
	"\x14probe/v1/probe.proto\x12\bprobe.v1\"\r\n" +
	"\vEchoRequest\"\x0e\n" +
	"\fEchoResponse2E\n" +
	"\fProbeService\x125\n" +
	"\x04Echo\x12\x15.probe.v1.EchoRequest\x1a\x16.probe.v1.EchoResponseB8Z6github.com/go-grpc-buf-base/pkg/grpc/probe/v1;probe_v1b\x06proto3"

var (
	file_probe_v1_probe_proto_rawDescOnce sync.Once
	file_probe_v1_probe_proto_rawDescData []byte
)

func file_probe_v1_probe_proto_rawDescGZIP() []byte {
	file_probe_v1_probe_proto_rawDescOnce.Do(func() {
		file_probe_v1_probe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_probe_v1_probe_proto_rawDesc), len(file_probe_v1_probe_proto_rawDesc)))
	})
	return file_probe_v1_probe_proto_rawDescData
}

var file_probe_v1_probe_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_probe_v1_probe_proto_goTypes = []any{
	(*EchoRequest)(nil),  // 0: probe.v1.EchoRequest
	(*EchoResponse)(nil), // 1: probe.v1.EchoResponse
}
var file_probe_v1_probe_proto_depIdxs = []int32{
	0, // 0: probe.v1.ProbeService.Echo:input_type -> probe.v1.EchoRequest
	1, // 1: probe.v1.ProbeService.Echo:output_type -> probe.v1.EchoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_probe_v1_probe_proto_init() }
func file_probe_v1_probe_proto_init() {
	if File_probe_v1_probe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_probe_v1_probe_proto_rawDesc), len(file_probe_v1_probe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_probe_v1_probe_proto_goTypes,
		DependencyIndexes: file_probe_v1_probe_proto_depIdxs,
		MessageInfos:      file_probe_v1_probe_proto_msgTypes,
	}.Build()
	File_probe_v1_probe_proto = out.File
	file_probe_v1_probe_proto_goTypes = nil
	file_probe_v1_probe_proto_depIdxs = nil
}
